CREATE TABLE [dbo].[OPENACCOUNTDETAIL] (
    [ibmb_ac_key]            VARCHAR (255)  NOT NULL,
    [fatca_status]           VARCHAR (255)  NULL,
    [pay_taxes_othercstatus] VARCHAR (255)  NULL,
    [roc_pay_man_status]     VARCHAR (255)  NULL,
    [acverinput_actno]       VARCHAR (255)  NULL,
    [acverinput_bank]        VARCHAR (255)  NULL,
    [address]                NVARCHAR (255) NULL,
    [address_code]           VARCHAR (255)  NULL,
    [agreement_deposite]     VARCHAR (255)  NULL,
    [agreement_open]         VARCHAR (255)  NULL,
    [agreement_personal]     VARCHAR (255)  NULL,
    [aml_result]             VARCHAR (255)  NULL,
    [apply_for]              VARCHAR (255)  NULL,
    [area]                   VARCHAR (255)  NULL,
    [birth_date]             VARCHAR (255)  NULL,
    [birth_month]            VARCHAR (255)  NULL,
    [birth_year]             VARCHAR (255)  NULL,
    [by_industry]            VARCHAR (255)  NULL,
    [by_job]                 VARCHAR (255)  NULL,
    [card_address]           NVARCHAR (255) NULL,
    [card_address_code]      VARCHAR (255)  NULL,
    [card_area]              VARCHAR (255)  NULL,
    [card_city]              VARCHAR (255)  NULL,
    [card_email]             VARCHAR (255)  NULL,
    [card_face]              VARCHAR (255)  NULL,
    [card_name]              NVARCHAR (255) NULL,
    [city]                   VARCHAR (255)  NULL,
    [comfirm_address]        NVARCHAR (255) NULL,
    [comfirm_address_code]   VARCHAR (255)  NULL,
    [comfirm_area]           VARCHAR (255)  NULL,
    [comfirm_birth_date]     VARCHAR (255)  NULL,
    [comfirm_birth_month]    VARCHAR (255)  NULL,
    [comfirm_birth_year]     VARCHAR (255)  NULL,
    [comfirm_city]           VARCHAR (255)  NULL,
    [comfirm_id_issue_city]  NVARCHAR (255) NULL,
    [comfirm_id_issue_date]  VARCHAR (255)  NULL,
    [comfirm_id_issue_month] VARCHAR (255)  NULL,
    [comfirm_id_issue_way]   NVARCHAR (255) NULL,
    [comfirm_id_issue_year]  VARCHAR (255)  NULL,
    [comfirm_idno]           VARCHAR (255)  NULL,
    [comfirm_name]           NVARCHAR (255) NULL,
    [company_name]           VARCHAR (255)  NULL,
    [device_record]          VARCHAR (255)  NULL,
    [first_back]             VARCHAR (255)  NULL,
    [first_front]            VARCHAR (255)  NULL,
    [gps]                    VARCHAR (255)  NULL,
    [id_issue_city]          NVARCHAR (255) NULL,
    [id_issue_date]          VARCHAR (255)  NULL,
    [id_issue_month]         VARCHAR (255)  NULL,
    [id_issue_way]           NVARCHAR (255) NULL,
    [id_issue_year]          VARCHAR (255)  NULL,
    [idno]                   VARCHAR (255)  NULL,
    [imei]                   VARCHAR (255)  NULL,
    [ipv4]                   VARCHAR (255)  NULL,
    [ipv6]                   VARCHAR (255)  NULL,
    [is_agree_agreement]     BIT            NULL,
    [is_modify]              BIT            NULL,
    [member_id]              VARCHAR (255)  NULL,
    [memo]                   VARCHAR (255)  NULL,
    [name]                   NVARCHAR (255) NULL,
    [ocr_sec_front]          VARCHAR (255)  NULL,
    [phone_number]           VARCHAR (255)  NULL,
    [psd]                    VARCHAR (255)  NULL,
    [sec_document_no]        VARCHAR (255)  NULL,
    [status]                 VARCHAR (255)  NULL,
    [step10update_date]      DATE           NULL,
    [step10update_time]      TIME (7)       NULL,
    [step11update_date]      DATE           NULL,
    [step11update_time]      TIME (7)       NULL,
    [step1update_date]       DATE           NULL,
    [step1update_time]       TIME (7)       NULL,
    [step2update_date]       DATE           NULL,
    [step2update_time]       TIME (7)       NULL,
    [step3update_date]       DATE           NULL,
    [step3update_time]       TIME (7)       NULL,
    [step4update_date]       DATE           NULL,
    [step4update_time]       TIME (7)       NULL,
    [step5update_date]       DATE           NULL,
    [step5update_time]       TIME (7)       NULL,
    [step6update_date]       DATE           NULL,
    [step6update_time]       TIME (7)       NULL,
    [step7update_date]       DATE           NULL,
    [step7update_time]       TIME (7)       NULL,
    [step8update_date]       DATE           NULL,
    [step8update_time]       TIME (7)       NULL,
    [step9update_date]       DATE           NULL,
    [step9update_time]       TIME (7)       NULL,
    [teller_check_date]      DATE           NULL,
    [teller_check_time]      TIME (7)       NULL,
    [teller_no]              VARCHAR (255)  NULL,
    [ver_aml]                VARCHAR (255)  NULL,
    [ver_amlsr]              VARCHAR (255)  NULL,
    [ver_fxml]               VARCHAR (255)  NULL,
    [ver_jcicz21]            VARCHAR (255)  NULL,
    [ver_jcicz21sr]          VARCHAR (255)  NULL,
    [ver_jcicz22]            VARCHAR (255)  NULL,
    [ver_jcicz22sr]          VARCHAR (255)  NULL,
    [ver_pcode2566]          VARCHAR (255)  NULL,
    [video_sound]            VARCHAR (255)  NULL,
    [video_view]             VARCHAR (255)  NULL,
    [z21result]              VARCHAR (255)  NULL,
    [z22result]              VARCHAR (255)  NULL,
    PRIMARY KEY CLUSTERED ([ibmb_ac_key] ASC)
);

